isam_input_file_name = 'isam/_Aux/input.txt';
fid = fopen(isam_input_file_name,'wt');

Perm = [    [ 0 , 1 , 0 ] ; ...
            [ 0 , 0 , 1 ] ; ...
            [ 1 , 0 , 0 ] ] ;
Q = diag([sigma_w^2 sigma_v^2,(sigma_v^2)/100]);
sqrt_info = Perm*inv(sqrt(Q(1:3,1:3)))*Perm';
sqrt_info_R = inv(sigma_p*eye(2));

already_seen = zeros(nL,1);
Feature2node = zeros(nL,1);
last_pos = 0;
current_pos = last_pos+1; 
for i=1:nSteps
    txt_line = ['ODOMETRY ',...
            num2str(last_pos), ' ',...
            num2str(current_pos), ' ',...
            num2str(v_m(i)), ' ',...
            num2str(0), ' ',...
            num2str(omega_m(i)), ' ',...
            num2str(sqrt_info(1,1)), ' ',...
            num2str(sqrt_info(1,2)), ' ',...
            num2str(sqrt_info(1,3)), ' ',...
            num2str(sqrt_info(2,2)), ' ',...
            num2str(sqrt_info(2,3)), ' ',...
            num2str(sqrt_info(3,3)), '\n' ];
    fprintf(fid,txt_line);
    
    last_pos = current_pos;
    current_pos = current_pos+1;
    z_i = z(:,:,i);
    visibles = zeros(nL,1);
    visibles(z_i(3,find(z_i(3,:)~=0))) = 1;
    new_features = (1-already_seen).*visibles;
    already_seen = already_seen + new_features;
    
    for jj = find(new_features)'
        Feature2node(jj) = current_pos;
        current_pos = current_pos+1;       
    end
    
    for jj=find(visibles)'
        pos = find(jj==z_i(3,:));
        txt_line = ['LANDMARK ',...
        num2str(last_pos), ' ',...
        num2str(Feature2node(jj)), ' ',...
        num2str(z_i(1,pos)), ' ',...
        num2str(z_i(2,pos)), ' ',...
        num2str(sqrt_info_R(1,1)), ' ',...
        num2str(sqrt_info_R(1,2)), ' ',...
        num2str(sqrt_info_R(2,2)), '\n' ];
    fprintf(fid,txt_line);
    end
    
end

fclose(fid);